rocket-paperplane-scissors-challenge/config/routes.rb
Rails.application.routes.draw do
  resources :games, except: [:edit, :update]
  root to: "games#index"
end

rocket-paperplane-scissors-challenge/app/models/game.rb
class Game < ActiveRecord::Base
  scope :recent, -> { order("created_at DESC").limit(5) }

  THROWS = %w(rock paper scissors)
  PLAYERS = %w(user computer)

  validates :computer_throw, presence: true,
    inclusion: { in: THROWS, message: "%{value} is not a valid throw" }

  validates :user_throw, presence: true,
    inclusion: { in: THROWS, message: "%{value} is not a valid throw" }

  validates :winner, presence: true,
    inclusion: { in: PLAYERS, message: "%{value} is not a valid player" }

  before_validation :throw_for_computer, on: :create

  def winner
    return "user" if user_throw_beats_computer_throw?
    return "computer"
  end

  def winner_throw
    return user_throw if user_won?
    return computer_throw
  end

  def loser_throw
    return computer_throw if user_won?
    return user_throw
  end

  def throw_for_computer
    self.computer_throw ||= THROWS.sample
  end

  def user_won?
    user_throw_beats_computer_throw?
  end

  private
  def user_throw_beats_computer_throw?
    return true if user_throw == 'paper' && computer_throw == 'rock'
    return true if user_throw == 'scissors' && computer_throw == 'paper'
    return true if user_throw == 'rock' && computer_throw == 'scissors'
    false
  end
end

rocket-paperplane-scissors-challenge/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rocket-paperplane-scissors-challenge/app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.recent
  end

  def show
    @game = Game.find(params[:id])
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)

    if @game.save
      redirect_to @game, notice: 'Game was successfully created.'
    else
      render :new, status: 422
    end
  end

  def destroy
    game = Game.find(params[:id])
    game.destroy
    redirect_to games_url, notice: 'Game was successfully destroyed.'
  end

  private
  def game_params
    params.require(:game).permit(:user_throw)
  end
end

rocket-paperplane-scissors-challenge/app/helpers/application_helper.rb
module ApplicationHelper
end

rocket-paperplane-scissors-challenge/app/helpers/games_helper.rb
module GamesHelper
  def headline(game)
    game.user_won? ? "User Won!!!" : "User Lost"
  end

  def result_for_user_throw(game)
    if game.user_won?
      active_result_for(game.user_throw)
    else
      passive_result_for(game.computer_throw)
    end
  end

  def throw_color(throw)
    return "danger" if throw == 'rock'
    return "success" if throw == 'paper'
    return "info" if throw == 'scissors'
  end

  def throw_fa_icon(throw)
    return "fa-hand-rock-o" if throw == "rock"
    return "fa-hand-stop-o" if throw == "paper"
    return "fa-hand-scissors-o" if throw == "scissors"
  end

  private
  def active_result_for(throw)
    return "covers" if throw == 'paper'
    return "cut" if throw == 'scissors'
    return "crushes" if throw == 'rock'
  end

  def passive_result_for(opposing_throw)
    return "is covered by" if opposing_throw == 'paper'
    return "is cut by" if opposing_throw == 'scissors'
    return "is crushed by" if opposing_throw == 'rock'
  end
end

rocket-paperplane-scissors-challenge/app/views/games/_form.html.erb
<%= form_for(@game, html: { class: 'form-inline new_game' }) do |f| %>
    <%= f.hidden_field :user_throw, value: throw %>
    <button id="throw-<%= throw %>" class="btn btn-<%= throw_color(throw) %> btn-lg">
        <i class="fa fa-5x <%= throw_fa_icon(throw) %>"></i>
      </button>
<% end %>

rocket-paperplane-scissors-challenge/app/views/games/index.html.erb
<h1>
  <span class="text-<%= throw_color('rock') %>">
    <i class="fa <%= throw_fa_icon('rock') %>"></i>Rock
  </span>,
  <span class="text-<%= throw_color('paper') %>">
    <i class="fa <%= throw_fa_icon('paper') %>"></i>Paper
  </span>,
  <span class="text-<%= throw_color('scissors') %>">
    <i class="fa <%= throw_fa_icon('scissors') %>"></i>Scissors
  </span>
</h1>

<p><strong><%= link_to 'New Game', new_game_path, class: 'btn btn-primary'  %></strong></p>

<ul class="inline recent-games">
  <% @games.each do |game| %>
    <p>
      <%= "#{game.computer_throw} vs. #{game.user_throw}" %>
      <br />
      Winner: <%= game.winner %>
      <br />
      <%= link_to 'Show', game %>
      <br />
      <%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
  <% end %>
</ul>

rocket-paperplane-scissors-challenge/app/views/games/new.html.erb
<h1>Ready &hellip; Set &hellip;</h1>

<% if @game.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

    <ul>
    <% @game.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= render partial: 'form', locals: { throw: 'rock' } %>
<%= render partial: 'form', locals: { throw: 'paper' } %>
<%= render partial: 'form', locals: { throw: 'scissors' } %>

<p><%= link_to 'Back', games_path %></p>

rocket-paperplane-scissors-challenge/app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= headline(@game) %></h2>
<p class="lead">
  <i class="fa fa-5x <%= throw_fa_icon(@game.user_throw) %> text-<%= throw_color(@game.user_throw) %>"></i>
  <span><strong><%= result_for_user_throw(@game) %></strong></span>
  <i class="fa fa-5x <%= throw_fa_icon(@game.computer_throw) %> text-<%= throw_color(@game.computer_throw) %>"></i>
</p>


<p><%= link_to 'New Game', new_game_path %></p>
<p><%= link_to 'Back', games_path %></p>

rocket-paperplane-scissors-challenge/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RockPaperScissors</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%= yield %>
    </div>
  </div>
</div>

</body>
</html>